"""Stage 2 (v2): self-play generation, replay buffer, human-mixed training and gated promotion (SPEC §6).

Games are generated with :class:`~flychess.train.mcts.BatchedMCTS` — up to ``cfg.selfplay_lockstep_games``
games of an iteration are searched in lockstep so every simulation step is one GPU forward (more games
run as several lockstep batches) — with Dirichlet noise at the root, temperature 1 for the first
``cfg.temperature_plies`` plies and argmax afterwards, no resignation, and ``cfg.max_game_plies`` as a
hard cap (counted as a draw). The subtree below the chosen move is kept between plies. With
``cfg.selfplay_workers > 1`` the games are split across that many threads, each running its own
lockstep batches on the shared model: PyTorch releases the GIL inside the CUDA kernels, so one thread's
tree work overlaps the other threads' GPU time. **Games are always generated by the best network.**

Training targets per self-play position: quantised planes (exactly the shard format of SPEC §5), ``pi`` =
the root visit distribution, ``z`` = the game result from the mover's perspective and ``q`` = the root
search value; the value target is ``blend · z + (1 - blend) · q`` (``cfg.selfplay_value_blend``). Every
training batch is ``cfg.selfplay_human_mix`` positions streamed from the imitation shards (one-hot
policy target = the stored move, unmasked cross-entropy exactly like stage 1, value target = the stored
value) and the rest replay-buffer samples, so the human/engine knowledge is rehearsed instead of
forgotten (the v1 stage, trained on self-play targets only, made the searching player weaker).

Gating: after an iteration's training the candidate plays the current best weights with ``superfly``
(:class:`~flychess.play.engine.FlyEngine`, ``cfg.selfplay_gate_sims`` simulations) on paired distinct
openings, both colours; it is promoted to best only if its score fraction reaches
``cfg.selfplay_gate_threshold``, otherwise the weights *and* the AdamW moments revert to their pre-training
snapshot (the replay buffer is kept and the iteration counts). A gate that cannot run (the evaluator raises or
returns nothing) rejects the candidate the same way and stops the stage with ``RuntimeError`` — an untested
candidate is never promoted. ``runs/<run>/best.pt`` always holds the best network; ``latest.pt`` equals it
after gating. The openings of the gate match come from the iteration's own games; only when those yield too
few distinct positions is the list topped up from :func:`fixed_openings` (20 standard first moves — the one
place a move not chosen by the fly enters a match; ``fixed_openings_used`` on the elo record says how many). The replay buffer stores ``pi`` sparsely (top-``k`` visited moves) together with the legal-move
indices so that the policy loss can mask illegal moves like the search does.

The fly brain is the only thing choosing moves in these games.
"""
from __future__ import annotations

import copy
import importlib
import inspect
import io
import logging
import math
import os
import shutil
import threading
import time
import warnings
from collections.abc import Callable, Iterator, Sequence
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

import chess
import chess.pgn
import numpy as np
import torch
from torch.utils.data import DataLoader

from flychess.chessenv.encoding import (
    FLAT_INPUT,
    NUM_MOVES,
    NUM_PLANES,
    board_features,
    index_to_move,
    planes_from_features,
)
from flychess.connectome.graph import BrainGraph
from flychess.data.shards import ShardDataset, collate, load_split, planes_to_float
from flychess.model.flybrain import FlyBrain, masked_policy_log_softmax
from flychess.train.imitation import ADAM_BETAS, adapt_optim_state, param_groups
from flychess.train.mcts import (
    BatchedMCTS,
    Node,
    advance_root,
    result_string,
    select_move_index,
    terminal_value,
)
from flychess.train.metrics import MetricsLogger

log = logging.getLogger(__name__)

_RESULT_Z = {"1-0": 1, "0-1": -1, "1/2-1/2": 0}
BEST = "best.pt"
PROGRESS_GAMES = 64          # a progress line / status record every this many finished games
GATE_OPPONENT = "previous-best"
LOCKSTEP_GAMES = 512         # default upper bound on the games searched in one lockstep batch


def _get(cfg: Any, name: str, default: Any) -> Any:
    """``cfg.name`` with a default so that a minimal config object (or a dict) works too."""
    if isinstance(cfg, dict):
        return cfg.get(name, default)
    return getattr(cfg, name, default)


# ------------------------------------------------------------------------------------------------
# Game record
# ------------------------------------------------------------------------------------------------
@dataclass
class Game:
    """One finished self-play game.

    ``planes`` uint8 (T, 20, 8, 8) shard-quantised · ``pi`` float16 (T, 4168) root visit distribution ·
    ``z`` int8 (T,) result from each mover's perspective · ``legal`` list of int16 arrays (legal move
    indices per position) · ``moves`` the UCI moves · ``pgn`` · ``result`` · ``plies`` · ``q`` float32 (T,)
    root search value from each mover's perspective (``None`` for games recorded without it).
    """

    planes: np.ndarray
    pi: np.ndarray
    z: np.ndarray
    legal: list[np.ndarray]
    moves: list[str]
    pgn: str
    result: str
    plies: int
    capped: bool = False
    meta: dict = field(default_factory=dict)
    q: np.ndarray | None = None

    def __len__(self) -> int:
        return self.plies


def _pgn(board: chess.Board, result: str, headers: dict[str, str] | None = None) -> str:
    game = chess.pgn.Game.from_board(board)
    game.headers["Event"] = "fly-chess self-play"
    game.headers["White"] = "fly"
    game.headers["Black"] = "fly"
    game.headers["Result"] = result
    for k, v in (headers or {}).items():
        game.headers[k] = v
    return str(game)


class _Live:
    """Bookkeeping of one in-progress self-play game."""

    __slots__ = ("board", "feats", "index", "legal", "moves", "pi", "q", "root", "turns")

    def __init__(self, index: int) -> None:
        self.index = index
        self.board = chess.Board()
        self.root: Node | None = None
        self.feats: list[np.ndarray] = []
        self.pi: list[tuple[np.ndarray, np.ndarray]] = []   # (legal_idx, probs over legal)
        self.legal: list[np.ndarray] = []
        self.turns: list[bool] = []
        self.moves: list[str] = []
        self.q: list[float] = []

    def finish(self, result: str, capped: bool) -> Game:
        T = len(self.feats)
        planes = planes_from_features(np.stack(self.feats), quantized=True) if T else np.zeros((0, NUM_PLANES, 8, 8), np.uint8)
        pi = np.zeros((T, NUM_MOVES), dtype=np.float16)
        for t, (li, p) in enumerate(self.pi):
            pi[t, li] = p
        z_white = _RESULT_Z[result]
        z = np.array([z_white if turn else -z_white for turn in self.turns], dtype=np.int8)
        return Game(planes=planes, pi=pi, z=z, legal=[li.astype(np.int16) for li in self.legal], moves=list(self.moves),
                    pgn=_pgn(self.board, result), result=result, plies=T, capped=capped,
                    q=np.asarray(self.q, dtype=np.float32))


def _play_batch(mcts: BatchedMCTS, indices: Sequence[int], cfg: Any, rng: np.random.Generator,
                on_game: Callable[[Game], None] | None) -> list[Game]:
    """Play ``len(indices)`` games to the end in lockstep; returns them in ``indices`` order."""
    temperature_plies = int(_get(cfg, "temperature_plies", 30))
    max_plies = int(_get(cfg, "max_game_plies", 300))
    live = [_Live(i) for i in indices]
    done: dict[int, Game] = {}
    active = list(live)
    while active:
        boards = [g.board for g in active]
        results = mcts.search(boards, roots=[g.root for g in active], add_noise=True)
        still: list[_Live] = []
        for g, res in zip(active, results, strict=True):
            ply = len(g.board.move_stack)
            finished: Game | None = None
            if res.terminal:  # cannot normally happen (we test after each push) but keeps the loop total
                finished = g.finish(result_string(g.board), capped=False)
            else:
                legal = res.root.moves.astype(np.int64)
                pol = res.visits[legal]
                pol = pol / pol.sum()
                g.feats.append(board_features(g.board))
                g.pi.append((legal, pol.astype(np.float32)))
                g.legal.append(legal)
                g.turns.append(g.board.turn)
                g.q.append(float(res.root_value))
                temperature = 1.0 if ply < temperature_plies else 0.0
                idx = res.best_index() if temperature <= 0 else select_move_index(res.visits, temperature, rng)
                move = index_to_move(idx, g.board)
                g.root = advance_root(res.root, move, g.board)
                g.board.push(move)
                g.moves.append(move.uci())
                if terminal_value(g.board) is not None:
                    finished = g.finish(result_string(g.board), capped=False)
                elif len(g.board.move_stack) >= max_plies:
                    finished = g.finish("1/2-1/2", capped=True)
            if finished is None:
                still.append(g)
            else:
                done[g.index] = finished
                if on_game is not None:
                    on_game(finished)
        active = still
    return [done[i] for i in indices]


def _play_chunks(mcts: BatchedMCTS, indices: Sequence[int], lockstep: int, cfg: Any, rng: np.random.Generator,
                 on_game: Callable[[Game], None] | None) -> list[Game]:
    """``indices`` split into lockstep batches of at most ``lockstep`` games, played one batch after the other."""
    out: list[Game] = []
    for start in range(0, len(indices), lockstep):
        out.extend(_play_batch(mcts, indices[start: start + lockstep], cfg, rng, on_game))
    return out


def generate_games(
    model: FlyBrain,
    graph: BrainGraph | None,
    cfg: Any,
    n_games: int,
    device: str | torch.device | None = None,
    rng: np.random.Generator | None = None,
    on_game: Callable[[Game], None] | None = None,
    sims: int | None = None,
    workers: int | None = None,
    lockstep: int | None = None,
) -> list[Game]:
    """Self-play ``n_games`` games with the fly brain (batched MCTS) and return them.

    ``graph`` is accepted for the shared contract (the model already carries the connectome) and may be
    ``None``. ``sims`` / ``workers`` / ``lockstep`` override ``cfg.mcts_sims`` / ``cfg.selfplay_workers`` /
    ``cfg.selfplay_lockstep_games`` (the most games searched in one lockstep batch; ``n_games`` above it
    are played as several consecutive batches — all in one batch when ``n_games <= lockstep``).
    """
    rng = rng if rng is not None else np.random.default_rng(int(_get(cfg, "seed", 0)))
    device = torch.device(device) if device is not None else next(model.parameters()).device
    sims = int(_get(cfg, "mcts_sims", 64) if sims is None else sims)
    workers = int(_get(cfg, "selfplay_workers", 1) if workers is None else workers)
    workers = max(1, min(workers, n_games)) if n_games > 0 else 1
    lockstep = max(1, int(_get(cfg, "selfplay_lockstep_games", LOCKSTEP_GAMES) if lockstep is None else lockstep))
    was_training = model.training
    model.eval()
    model.structure()  # build the device-side CSR views once, before any thread touches them
    try:
        make = lambda seed: BatchedMCTS(
            model, device, sims=sims, c_puct=float(_get(cfg, "c_puct", 1.5)),
            dirichlet_alpha=float(_get(cfg, "dirichlet_alpha", 0.3)), dirichlet_eps=float(_get(cfg, "dirichlet_eps", 0.25)),
            rng=np.random.default_rng(seed),
        )
        if workers == 1:
            mcts = make(int(rng.integers(2**31)))
            return _play_chunks(mcts, list(range(n_games)), lockstep, cfg, rng, on_game)
        chunks = [list(range(n_games))[w::workers] for w in range(workers)]
        seeds = rng.integers(2**31, size=2 * workers)
        games: list[Game | None] = [None] * n_games
        with ThreadPoolExecutor(max_workers=workers, thread_name_prefix="selfplay") as pool:
            futures = [pool.submit(_play_chunks, make(int(seeds[w])), chunks[w], lockstep, cfg,
                                   np.random.default_rng(int(seeds[workers + w])), on_game)
                       for w in range(workers) if chunks[w]]
            for w, fut in enumerate(futures):
                for i, game in zip(chunks[w], fut.result(), strict=True):
                    games[i] = game
        return [g for g in games if g is not None]
    finally:
        model.train(was_training)


# ------------------------------------------------------------------------------------------------
# Replay buffer
# ------------------------------------------------------------------------------------------------
class ReplayBuffer:
    """Ring buffer of self-play positions.

    Stores ``planes`` (uint8, shard format), ``pi`` sparsely as the top-``k`` visited moves (index +
    float16 probability, renormalised), the legal move indices (``int16`` padded with -1, at most
    ``lmax`` — moves carrying ``pi`` mass are kept first), ``z`` (int8, the game outcome) and ``q``
    (float16, the root search value; equal to ``z`` for games recorded without one).
    """

    def __init__(self, size: int, k: int = 64, lmax: int = 128, seed: int = 0) -> None:
        self.size = int(size)
        self.k = int(k)
        self.lmax = int(lmax)
        self.planes = np.zeros((self.size, NUM_PLANES, 8, 8), dtype=np.uint8)
        self.pi_idx = np.zeros((self.size, self.k), dtype=np.int16)
        self.pi_val = np.zeros((self.size, self.k), dtype=np.float16)
        self.legal = np.full((self.size, self.lmax), -1, dtype=np.int16)
        self.z = np.zeros(self.size, dtype=np.int8)
        self.q = np.zeros(self.size, dtype=np.float16)
        self.pos = 0
        self.count = 0
        self.games = 0
        self.rng = np.random.default_rng(seed)

    def __len__(self) -> int:
        return self.count

    def add(self, game: Game) -> int:
        """Append every position of ``game``; returns the number of positions added."""
        T = game.plies
        if T == 0:
            return 0
        pi = game.pi.astype(np.float32)
        top = np.argsort(-pi, axis=1)[:, : self.k]                        # (T, k)
        val = np.take_along_axis(pi, top, axis=1)
        val = val / np.maximum(val.sum(axis=1, keepdims=True), 1e-8)
        legal = np.full((T, self.lmax), -1, dtype=np.int16)
        for t in range(T):
            li = np.asarray(game.legal[t], dtype=np.int64)
            if li.shape[0] > self.lmax:  # keep the moves that carry probability mass first
                order = np.argsort(-pi[t, li], kind="stable")
                li = li[order][: self.lmax]
            legal[t, : li.shape[0]] = li
        q = game.q if game.q is not None and len(game.q) == T else game.z.astype(np.float32)
        self.games += 1
        for t in range(T):  # ring write (positions are contiguous unless we wrap)
            p = self.pos
            self.planes[p] = game.planes[t]
            self.pi_idx[p] = top[t]
            self.pi_val[p] = val[t]
            self.legal[p] = legal[t]
            self.z[p] = game.z[t]
            self.q[p] = q[t]
            self.pos = (p + 1) % self.size
        self.count = min(self.size, self.count + T)
        return T

    def sample(self, batch: int, rng: np.random.Generator | None = None, value_blend: float = 1.0
               ) -> dict[str, torch.Tensor]:
        """Uniform sample: ``planes float32 (B, 1280)``, ``pi float32 (B, 4168)``, ``z float32 (B,)`` (the value
        target ``value_blend · outcome + (1 - value_blend) · q``), ``outcome``, ``q`` and ``legal_mask bool (B, 4168)``."""
        if self.count == 0:
            raise ValueError("replay buffer is empty")
        rng = rng if rng is not None else self.rng
        idx = rng.integers(0, self.count, size=int(batch))
        planes = planes_to_float(self.planes[idx]).reshape(len(idx), FLAT_INPUT)
        pi = np.zeros((len(idx), NUM_MOVES), dtype=np.float32)
        rows = np.arange(len(idx))[:, None]
        pi_idx = self.pi_idx[idx].astype(np.int64)
        np.add.at(pi, (np.broadcast_to(rows, pi_idx.shape), pi_idx), self.pi_val[idx].astype(np.float32))
        legal = self.legal[idx].astype(np.int64)
        mask = np.zeros((len(idx), NUM_MOVES), dtype=bool)
        ok = legal >= 0
        mask[np.broadcast_to(rows, legal.shape)[ok], legal[ok]] = True
        mask |= pi > 0
        outcome = self.z[idx].astype(np.float32)
        q = self.q[idx].astype(np.float32)
        blend = float(value_blend)
        z = blend * outcome + (1.0 - blend) * q
        return {
            "planes": torch.from_numpy(planes),
            "pi": torch.from_numpy(pi),
            "z": torch.from_numpy(z.astype(np.float32)),
            "outcome": torch.from_numpy(outcome),
            "q": torch.from_numpy(q),
            "legal_mask": torch.from_numpy(mask),
        }


# ------------------------------------------------------------------------------------------------
# Human data rehearsal: a stream over the imitation shards and the mixed batch
# ------------------------------------------------------------------------------------------------
class HumanStream:
    """An endless stream of ``batch``-sized batches from the imitation shards of ``cfg`` (SPEC §5 format).

    Uses ``load_split(cfg.shards_dir, cfg.val_fraction, cfg.seed, cfg.shard_name)`` (the training side, so
    the ``shard_name`` series and repeat factors apply exactly as in stage 1) and a shuffling
    :class:`ShardDataset`; the shard permutation changes every pass (``set_epoch``). Batches are the
    ``collate`` dicts (``planes float32 (B, 1280)``, ``move int64``, ``value float32``, ...).
    """

    def __init__(self, cfg: Any, batch: int, device: torch.device | None = None, seed: int = 0,
                 files: Sequence[str | Path] | None = None) -> None:
        if files is None:
            files, _ = load_split(str(_get(cfg, "shards_dir", "data/shards")), float(_get(cfg, "val_fraction", 0.02)),
                                  int(_get(cfg, "seed", 0)), _get(cfg, "shard_name", None))
        self.files = [Path(f) for f in files]
        if not self.files:
            raise FileNotFoundError("no imitation shards to mix into self-play training")
        self.batch = int(batch)
        self.epoch = 0
        self.positions = 0
        self.dataset = ShardDataset(self.files, seed=seed, shuffle=True)
        workers = min(int(_get(cfg, "num_workers", 0)), len(self.files), 2)
        kwargs: dict[str, Any] = {"prefetch_factor": 4} if workers > 0 else {}
        self.loader = DataLoader(self.dataset, batch_size=self.batch, collate_fn=collate, num_workers=workers,
                                 drop_last=True, pin_memory=device is not None and device.type == "cuda", **kwargs)
        self._it: Iterator[dict[str, torch.Tensor]] | None = None

    def next(self) -> dict[str, torch.Tensor]:
        """The next batch; a new pass (reshuffled) starts when the shards are exhausted."""
        for _ in range(2):
            if self._it is None:
                self.dataset.set_epoch(self.epoch)
                self._it = iter(self.loader)
            try:
                batch = next(self._it)
            except StopIteration:
                self._it = None
                self.epoch += 1
                continue
            self.positions += int(batch["move"].shape[0])
            return batch
        raise RuntimeError(f"the imitation shards yield no full batch of {self.batch} positions")

    __next__ = next

    def __iter__(self) -> HumanStream:
        return self


def human_targets(batch: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
    """Self-play-style targets of a shard ``collate`` batch: one-hot ``pi`` on the stored move, an all-``True``
    ``legal_mask`` (stage 1 trains the *unmasked* softmax; the batch is treated the same way here) and ``z`` =
    the stored value (outcome or engine evaluation in [-1, 1])."""
    move = batch["move"].to(torch.int64).view(-1)
    B = move.shape[0]
    pi = torch.zeros(B, NUM_MOVES, dtype=torch.float32)
    pi[torch.arange(B), move] = 1.0
    return {"planes": batch["planes"].float(), "pi": pi, "z": batch["value"].float().view(-1),
            "legal_mask": torch.ones(B, NUM_MOVES, dtype=torch.bool)}


def make_mixed_batch(buffer: ReplayBuffer | None, human: HumanStream | None, batch_size: int, human_mix: float,
                     value_blend: float = 1.0, rng: np.random.Generator | None = None) -> dict[str, Any]:
    """One training batch: the first ``n_self`` rows are replay-buffer samples (``pi`` = visit distribution,
    ``z`` = blended value target, legal mask), the remaining ``round(batch_size · human_mix)`` rows come from
    the human stream (:func:`human_targets`). Returns ``{planes, pi, z, legal_mask, n_self, n_human}``."""
    batch_size = int(batch_size)
    n_human = round(batch_size * float(human_mix)) if human is not None else 0
    n_human = min(max(n_human, 0), batch_size)
    n_self = batch_size - n_human
    parts: list[dict[str, torch.Tensor]] = []
    if n_self > 0:
        if buffer is None or len(buffer) == 0:
            raise ValueError("replay buffer is empty")
        parts.append(buffer.sample(n_self, rng, value_blend=value_blend))
    if n_human > 0:
        hb = human.next()
        if int(hb["move"].shape[0]) != n_human:  # a stream built for another batch size
            raise ValueError(f"human stream yields batches of {int(hb['move'].shape[0])}, expected {n_human}")
        parts.append(human_targets(hb))
    keys = ("planes", "pi", "z", "legal_mask")
    out: dict[str, Any] = {k: torch.cat([p[k] for p in parts], dim=0) if len(parts) > 1 else parts[0][k] for k in keys}
    out["n_self"] = n_self
    out["n_human"] = n_human
    return out


# ------------------------------------------------------------------------------------------------
# Loss
# ------------------------------------------------------------------------------------------------
def selfplay_loss(logits: torch.Tensor, value: torch.Tensor, pi: torch.Tensor, z: torch.Tensor,
                  legal_mask: torch.Tensor | None = None, value_weight: float = 1.0
                  ) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """``-(pi · log_softmax(logits)) + value_weight · mse(value, z)`` with illegal moves masked out.

    Returns ``(loss, metrics)``; metrics are detached device tensors (``loss, policy_loss, value_loss,
    top1, top3`` where top-k compares the network's argmax with the search's most visited move).
    """
    loss, metrics, _ = _row_losses(logits, value, pi, z, legal_mask, value_weight)
    return loss, metrics


def _row_losses(logits: torch.Tensor, value: torch.Tensor, pi: torch.Tensor, z: torch.Tensor,
                legal_mask: torch.Tensor | None, value_weight: float
                ) -> tuple[torch.Tensor, dict[str, torch.Tensor], dict[str, torch.Tensor]]:
    """The loss of :func:`selfplay_loss` plus the detached per-row terms (``policy``, ``value``, ``hit1``, ``hit3``)."""
    logp = masked_policy_log_softmax(logits, legal_mask)
    if legal_mask is not None:
        logp = logp.masked_fill(~legal_mask.to(torch.bool), 0.0)   # pi is 0 there: avoid 0 * -inf
    row_policy = -(pi.float() * logp).sum(dim=-1)
    v = value.float().view(-1)
    row_value = (v - z.float().view(-1)) ** 2
    policy_loss = row_policy.mean()
    value_loss = row_value.mean()
    loss = policy_loss + value_weight * value_loss
    with torch.no_grad():
        target = pi.argmax(dim=-1)
        top3 = logp.masked_fill(~legal_mask.to(torch.bool), float("-inf")).topk(3, dim=-1).indices if legal_mask is not None else logp.topk(3, dim=-1).indices
        hit = top3 == target.unsqueeze(1)
        metrics = {"loss": loss.detach(), "policy_loss": policy_loss.detach(), "value_loss": value_loss.detach(),
                   "top1": hit[:, 0].float().mean(), "top3": hit.any(dim=1).float().mean()}
        rows = {"policy": row_policy.detach(), "value": row_value.detach(), "hit1": hit[:, 0].float(),
                "hit3": hit.any(dim=1).float()}
    return loss, metrics, rows


def mixed_loss(logits: torch.Tensor, value: torch.Tensor, batch: dict[str, Any], value_weight: float = 1.0,
               halves: bool = True) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """:func:`selfplay_loss` on a :func:`make_mixed_batch` batch (targets already on the model's device).

    The loss is the plain mean over all rows (self-play rows: masked cross-entropy against the visit
    distribution; human rows: unmasked cross-entropy against the stored move, as in stage 1). With
    ``halves`` the metrics add the per-half means ``policy_loss_self / value_loss_self / top1_self`` and
    ``..._human`` when the batch has both halves (a second, gradient-free pass over the logits: ask for it on
    the steps that are logged).
    """
    pi, z, mask = batch["pi"], batch["z"], batch.get("legal_mask")
    loss, metrics = selfplay_loss(logits, value, pi, z, mask, value_weight)
    n_self = int(batch.get("n_self", pi.shape[0]))
    n_human = int(batch.get("n_human", 0))
    if halves and n_self > 0 and n_human > 0:
        with torch.no_grad():
            rows = _row_losses(logits.detach(), value.detach(), pi, z, mask, value_weight)[2]
        for name, sl in (("self", slice(0, n_self)), ("human", slice(n_self, n_self + n_human))):
            metrics[f"policy_loss_{name}"] = rows["policy"][sl].mean()
            metrics[f"value_loss_{name}"] = rows["value"][sl].mean()
            metrics[f"top1_{name}"] = rows["hit1"][sl].mean()
    return loss, metrics


# ------------------------------------------------------------------------------------------------
# Evaluation: gate (candidate vs best), previous iteration and a random opponent
# ------------------------------------------------------------------------------------------------
def elo_from_score(score: float) -> float:
    """Elo difference implied by a score fraction (clamped to ±800)."""
    s = min(max(score, 0.01), 0.99)
    return float(-400.0 * math.log10(1.0 / s - 1.0))


def play_match(player_a: Any, player_b: Any, games: int, max_plies: int = 300, seed: int = 0,
               on_game: Callable[[int, str, str], None] | None = None, keep_pgns: int = 3,
               start_fens: Sequence[str] | None = None) -> dict[str, Any]:
    """``games`` games between two ``Player``-protocol objects (colours alternate) → W/D/L for A + Elo diff.

    Same signature as ``flychess.eval.elo.play_match`` (used when that module is unavailable): game ``i``
    starts from ``start_fens[i % len(start_fens)]`` when given, ``seed`` reseeds players exposing ``rng``,
    ``on_game(index, result, pgn)`` fires per game and the first ``keep_pgns`` PGNs are returned.
    """
    for k, player in enumerate((player_a, player_b)):
        if getattr(player, "rng", None) is not None:
            player.rng = np.random.default_rng(seed * 2 + k)
    wins = draws = losses = truncated = 0
    plies: list[int] = []
    pgns: list[str] = []
    for g in range(games):
        board = chess.Board(start_fens[g % len(start_fens)]) if start_fens else chess.Board()
        a_white = g % 2 == 0
        while terminal_value(board) is None and len(board.move_stack) < max_plies:
            player = player_a if (board.turn == chess.WHITE) == a_white else player_b
            board.push(player.choose(board))
        truncated += terminal_value(board) is None
        plies.append(len(board.move_stack))
        result = result_string(board)
        result = result if result != "*" else "1/2-1/2"
        z = _RESULT_Z[result]
        if not a_white:
            z = -z
        wins += z > 0
        draws += z == 0
        losses += z < 0
        pgn = ""
        if g < keep_pgns or on_game is not None:
            pgn = _pgn(board, result, {"White": player_a.name if a_white else player_b.name,
                                       "Black": player_b.name if a_white else player_a.name, "Round": str(g + 1)})
            if g < keep_pgns:
                pgns.append(pgn)
        if on_game is not None:
            on_game(g, result, pgn)
    score = (wins + 0.5 * draws) / max(1, games)
    return {"player_a": player_a.name, "player_b": player_b.name, "games": games, "wins": wins, "draws": draws,
            "losses": losses, "score": score, "elo_estimate": elo_from_score(score), "pgns": pgns,
            "pgn": pgns[0] if pgns else "", "truncated": truncated,
            "mean_plies": (sum(plies) / len(plies)) if plies else 0.0}


def opening_fens(games: Sequence[Game], n: int, rng: np.random.Generator, min_ply: int = 8, max_ply: int = 12
                 ) -> list[str]:
    """Up to ``n`` distinct non-terminal positions taken from ``games`` (the FEN after ``min_ply``…``max_ply``
    plies of each game, capped at the game's penultimate ply) — the openings of an evaluation match.

    Deterministic players (``fly`` / ``superfly``) always play the same game from the start position, so a
    match between two of them needs distinct openings for its games to carry any information.
    """
    out: list[str] = []
    seen: set[str] = set()
    for gi in rng.permutation(len(games)):
        g = games[int(gi)]
        if g.plies <= 0:
            continue
        k = int(min(rng.integers(min_ply, max_ply + 1), g.plies - 1))
        board = chess.Board()
        for uci in g.moves[:k]:
            board.push_uci(uci)
        if terminal_value(board) is not None:  # cannot happen for k < plies, but never hand out a finished game
            continue
        fen = board.fen()
        if fen not in seen:
            seen.add(fen)
            out.append(fen)
        if len(out) >= n:
            break
    return out


_FIXED_OPENINGS = (
    "e4 e5", "d4 d5", "e4 c5", "d4 Nf6", "c4 e5", "e4 e6", "d4 d5 c4", "e4 c6", "Nf3 d5", "e4 e5 Nf3 Nc6",
    "d4 Nf6 c4 g6", "e4 e5 Nf3 Nc6 Bb5", "e4 c5 Nf3 d6", "d4 Nf6 c4 e6", "e4 d5", "c4 c5", "d4 f5", "e4 e5 Nc3",
    "Nf3 Nf6", "e4 g6",
)


@lru_cache(maxsize=1)
def fixed_openings() -> tuple[str, ...]:
    """A fixed set of 20 distinct opening positions (a few standard first moves) for evaluation matches when an
    iteration's own games do not provide enough distinct openings."""
    fens = []
    for line in _FIXED_OPENINGS:
        board = chess.Board()
        for san in line.split():
            board.push_san(san)
        fens.append(board.fen())
    return tuple(fens)


def _match_openings(games: Sequence[Game], n: int, rng: np.random.Generator) -> tuple[list[str], int]:
    """:func:`match_openings` plus the number of openings that came from the fixed set."""
    out = opening_fens(games, n, rng) if games else []
    seen = set(out)
    n_fixed = 0
    for fen in fixed_openings():
        if len(out) >= n:
            break
        if fen not in seen:
            seen.add(fen)
            out.append(fen)
            n_fixed += 1
    return out, n_fixed


def match_openings(games: Sequence[Game], n: int, rng: np.random.Generator) -> list[str]:
    """``n`` distinct openings: from the games (:func:`opening_fens`) first, topped up from :func:`fixed_openings`
    (the fly plays every move *from* these positions; the top-up is the only source of moves it did not choose)."""
    return _match_openings(games, n, rng)[0]


def paired_start_fens(openings: Sequence[str], games: int) -> list[str] | None:
    """Every opening twice in a row (game ``2j`` / ``2j+1`` swap colours), cycling if there are too few."""
    if not openings or games <= 0:
        return None
    return [openings[(i // 2) % len(openings)] for i in range(games)]


def _match_fn() -> Callable[..., Any]:
    """``flychess.eval.elo.play_match`` when importable, else the built-in matcher above."""
    try:
        elo_mod = importlib.import_module("flychess.eval.elo")
        fn = getattr(elo_mod, "play_match", None)
        if callable(fn):
            return fn
    except Exception as e:  # noqa: BLE001 - the eval package belongs to another module; anything odd → fallback
        log.debug("flychess.eval.elo.play_match unavailable (%r): using the built-in match", e)
    return play_match


def _match_kwargs(match_fn: Callable[..., Any], wanted: dict[str, Any]) -> dict[str, Any]:
    """The subset of ``wanted`` keyword arguments that ``match_fn`` accepts (all of them for ``**kwargs``)."""
    try:
        params = inspect.signature(match_fn).parameters
    except (TypeError, ValueError):  # a builtin / C callable without a signature: positional call only
        return {}
    if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values()):
        return dict(wanted)
    return {k: v for k, v in wanted.items() if k in params}


def _run_match(player_a: Any, player_b: Any, games: int, max_plies: int, start_fens: Sequence[str] | None,
               seed: int) -> dict[str, Any] | None:
    """Play the match with the shared evaluator (or the fallback) and normalise the result to a dict.

    The call form follows the evaluator's signature (an evaluator without ``start_fens`` plays from the initial
    position and the record says ``openings=1``); an exception raised *inside* the match propagates — it is never
    replayed with other arguments.
    """
    match_fn = _match_fn()
    kwargs = _match_kwargs(match_fn, {"max_plies": max_plies, "seed": seed, "start_fens": start_fens,
                                      "keep_pgns": games})
    out = match_fn(player_a, player_b, games, **kwargs)
    used_fens = start_fens if "start_fens" in kwargs else None
    if hasattr(out, "to_dict"):
        pgns = list(getattr(out, "pgns", []) or [])
        out = out.to_dict()
        out["pgns"] = pgns
    if not isinstance(out, dict) or "wins" not in out:
        warnings.warn("play_match returned an unexpected result; skipping the elo record", stacklevel=2)
        return None
    out["openings"] = len(set(used_fens)) if used_fens else 1
    return out


def _evaluate_vs_previous(model: FlyBrain, prev_state: dict[str, torch.Tensor], graph: BrainGraph, cfg: Any,
                          device: torch.device, games: int, start_fens: Sequence[str] | None = None,
                          seed: int = 0) -> dict[str, Any] | None:
    """Current model vs the previous iteration's weights, both playing as ``fly`` (policy + 1-ply value).

    ``fly`` is deterministic, so ``start_fens`` (see :func:`opening_fens` / :func:`paired_start_fens`)
    must vary the openings for the match to be more than one game per colour.
    """
    try:
        from flychess.play.engine import FlyEngine
    except ImportError as e:  # pragma: no cover
        warnings.warn(f"evaluation skipped: {e}", stacklevel=2)
        return None
    prev = FlyBrain(graph, model.config).to(device)
    prev.load_state_dict(prev_state)
    prev.eval()
    current = FlyEngine(model, graph, device).as_player("fly")
    previous = FlyEngine(prev, graph, device).as_player("fly")
    current.name, previous.name = "current", "previous"
    try:
        return _run_match(current, previous, games, int(_get(cfg, "max_game_plies", 300)), start_fens, seed)
    finally:
        del prev


def _evaluate_vs_random(model: FlyBrain, graph: BrainGraph, cfg: Any, device: torch.device, games: int,
                        start_fens: Sequence[str] | None = None, seed: int = 0) -> dict[str, Any] | None:
    """The current model (``fly``) against ``flychess.eval.opponents.RandomPlayer`` — an *opponent*, SPEC §6."""
    try:
        from flychess.eval.opponents import RandomPlayer
        from flychess.play.engine import FlyEngine
    except ImportError as e:
        warnings.warn(f"evaluation vs random skipped: {e}", stacklevel=2)
        return None
    current = FlyEngine(model, graph, device).as_player("fly")
    current.name = "current"
    return _run_match(current, RandomPlayer(seed=seed, name="random"), games,
                      int(_get(cfg, "max_game_plies", 300)), start_fens, seed)


def gate_candidate(model: FlyBrain, best_state: dict[str, torch.Tensor], graph: BrainGraph, cfg: Any,
                   device: torch.device, games: int, sims: int, threshold: float,
                   start_fens: Sequence[str] | None = None, seed: int = 0) -> dict[str, Any] | None:
    """The candidate (``model``'s current weights) against the best weights, both as ``superfly`` with ``sims``
    simulations, on ``start_fens`` (paired openings, both colours). Returns the match dict (candidate's W/D/L,
    ``score``, ``threshold`` and ``promoted = score >= threshold``) or ``None`` when no match could be played.

    Both players are deterministic (no root noise, argmax of the visits), so distinct paired openings are
    what makes the games differ; the caller decides what to do with ``promoted``.
    """
    try:
        from flychess.play.engine import FlyEngine
    except ImportError as e:  # pragma: no cover
        warnings.warn(f"gate skipped: {e}", stacklevel=2)
        return None
    was_training = model.training
    model.eval()
    best = FlyBrain(graph, model.config).to(device)
    best.load_state_dict(best_state)
    best.eval()
    candidate = FlyEngine(model, graph, device, sims=int(sims), seed=seed).as_player("superfly")
    incumbent = FlyEngine(best, graph, device, sims=int(sims), seed=seed + 1).as_player("superfly")
    candidate.name, incumbent.name = "candidate", "best"
    try:
        out = _run_match(candidate, incumbent, int(games), int(_get(cfg, "max_game_plies", 300)), start_fens, seed)
    finally:
        del best
        model.train(was_training)
    if out is None:
        return None
    out["score"] = (float(out["wins"]) + 0.5 * float(out["draws"])) / max(1, int(out["games"]))
    out["threshold"] = float(threshold)
    out["promoted"] = bool(out["score"] >= float(threshold))
    out["sims"] = int(sims)
    return out


# ------------------------------------------------------------------------------------------------
# Stage 2 loop
# ------------------------------------------------------------------------------------------------
def _gpu_mem_gb(device: torch.device) -> float:
    if device.type == "cuda":
        return float(torch.cuda.max_memory_allocated(device)) / 1e9
    return 0.0


def _sample_activity(model: FlyBrain, board: chess.Board, device: torch.device, n: int = 2048
                     ) -> tuple[np.ndarray, np.ndarray]:
    x = torch.from_numpy(planes_from_features(board_features(board)[None]).reshape(1, -1)).to(device)
    with torch.no_grad():
        _, _, h = model(x, return_activity=True)
    h = h[0].float().cpu().numpy()
    idx = np.linspace(0, h.shape[0] - 1, num=min(n, h.shape[0]), dtype=np.int64)
    return idx, h[idx]


def completed_iterations(run_dir: str | Path, step: int) -> int:
    """Self-play iterations already finished at ``step`` according to the run's metrics.

    Every finished iteration writes a ``status`` record ``{stage: 'selfplay', iteration: n}``; the
    largest ``n`` at or before ``step`` is returned (0 when the run has no such record).
    """
    try:
        from flychess.train.metrics import read_metrics
    except ImportError:  # pragma: no cover
        return 0
    done = 0
    for rec in read_metrics(run_dir, kinds=["status"]):
        if rec.get("stage") == "selfplay" and rec.get("iteration") is not None and int(rec.get("step", -1)) <= step:
            done = max(done, int(rec["iteration"]))
    return done


def _resume_optim_state(run_dir: Path, step: int) -> dict | None:
    """The optimizer state of ``<run_dir>/latest.pt`` when it is a self-play checkpoint saved at ``step``."""
    latest = run_dir / "latest.pt"
    if not latest.exists():
        return None
    try:
        ck = torch.load(latest, map_location="cpu", weights_only=False)
    except Exception as e:  # noqa: BLE001 - a corrupt/foreign checkpoint must not stop the stage
        log.warning("could not read %s for the optimizer state: %r", latest, e)
        return None
    if ck.get("stage") == "selfplay" and int(ck.get("step", -1)) == int(step) and isinstance(ck.get("optim"), dict):
        return ck["optim"]
    return None


def _load_best(run_dir: Path, model: FlyBrain) -> int | None:
    """Load the weights of ``<run_dir>/best.pt`` into ``model``; returns the checkpoint's step, ``None`` if absent
    or unusable (a warning says why)."""
    path = run_dir / BEST
    if not path.exists():
        return None
    try:
        ck = torch.load(path, map_location="cpu", weights_only=False)
        model.load_state_dict(ck["model"])
    except Exception as e:  # noqa: BLE001 - a foreign / corrupt best.pt must not stop the stage
        warnings.warn(f"{path} could not be loaded ({e!r}): continuing with the weights of latest.pt", stacklevel=2)
        return None
    return int(ck.get("step", -1))


def _copy_optim_state(state: dict[str, Any]) -> dict[str, Any]:
    """A deep CPU copy of an optimizer ``state_dict`` (the AdamW moments and step counts) that no later
    ``optim.step()`` can change — the pre-training snapshot restored when a candidate is rejected."""
    moments = {k: {kk: (vv.detach().to("cpu", copy=True) if isinstance(vv, torch.Tensor) else copy.deepcopy(vv))
                   for kk, vv in v.items()} for k, v in state["state"].items()}
    return {"state": moments, "param_groups": copy.deepcopy(state["param_groups"])}


def _restore_optim(optim: torch.optim.Optimizer, snapshot: dict[str, Any] | None) -> None:
    """Put the optimizer back to ``snapshot`` (a :func:`_copy_optim_state`); a copy is loaded so the snapshot stays
    untouched by later steps."""
    if snapshot is not None:
        optim.load_state_dict(_copy_optim_state(snapshot))


def _save(save_checkpoint: Callable[..., Path], step: int, stage: str, optim: torch.optim.Optimizer) -> Path:
    """``save_checkpoint(step, stage, optim=...)`` when the callback accepts an optimizer, else without it."""
    try:
        params = inspect.signature(save_checkpoint).parameters
        takes_optim = "optim" in params or any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values())
    except (TypeError, ValueError):
        takes_optim = False
    if takes_optim:
        return save_checkpoint(step, stage, optim=optim)
    return save_checkpoint(step, stage)


def _save_best(run_dir: Path, ckpt_path: Path | None) -> Path | None:
    """Copy the checkpoint just written (the best weights) to ``<run_dir>/best.pt`` (atomically)."""
    if ckpt_path is None or not Path(ckpt_path).is_file():
        return None
    run_dir.mkdir(parents=True, exist_ok=True)
    target = run_dir / BEST
    tmp = run_dir / f"{BEST}.tmp{os.getpid()}"
    shutil.copyfile(ckpt_path, tmp)
    os.replace(tmp, target)
    return target


class _Progress:
    """Counts the finished games of an iteration (thread-safe: ``selfplay_workers`` threads call it) and writes a
    progress line + ``status`` record (pos/s, ETA) every :data:`PROGRESS_GAMES` games and at the last one."""

    def __init__(self, logger: MetricsLogger, it: int, iters: int, total_games: int, step: int, total_steps: int) -> None:
        self.logger, self.it, self.iters, self.total_games = logger, it, iters, total_games
        self.step, self.total_steps = step, total_steps
        self.games = 0
        self.positions = 0
        self.t0 = time.time()
        self.lock = threading.Lock()

    def __call__(self, game: Game) -> None:
        with self.lock:
            self.games += 1
            self.positions += game.plies
            n, pos = self.games, self.positions
        if n % PROGRESS_GAMES == 0 or n == self.total_games:
            el = time.time() - self.t0
            rate = pos / max(el, 1e-9)
            log.info("selfplay iter %d: %d/%d games, %d positions in %.0fs (%.1f pos/s)", self.it, n, self.total_games,
                     pos, el, rate)
            self.logger.log_status(self.step, message=f"self-play iteration {self.it + 1}/{self.iters}: {n}/"
                                   f"{self.total_games} games ({rate:.0f} pos/s)", stage="selfplay",
                                   total_steps=self.total_steps, eta_s=el / n * (self.total_games - n))


@dataclass
class _TrainParams:
    """The static knobs of the training phase of an iteration (see :func:`_train_iteration`)."""

    steps: int
    batch_size: int
    human_mix: float
    value_blend: float
    value_weight: float
    grad_clip: float
    amp: bool
    log_every: int
    device: torch.device
    total_steps: int
    start_step: int


def _train_iteration(model: FlyBrain, optim: torch.optim.Optimizer, buffer: ReplayBuffer, human: HumanStream | None,
                     p: _TrainParams, rng: np.random.Generator, logger: MetricsLogger, step: int, it: int
                     ) -> tuple[int, dict[str, float]]:
    """``p.steps`` AdamW steps on mixed batches; returns ``(step, last metrics)``. Raises ``RuntimeError`` on a
    non-finite loss (before the model is updated with it)."""
    model.train()
    t_train = time.time()
    seen = 0
    last: dict[str, float] = {}
    try:
        for _ in range(p.steps):
            batch = make_mixed_batch(buffer, human, p.batch_size, p.human_mix, p.value_blend, rng)
            nb = p.device.type == "cuda"
            targets = {k: batch[k].to(p.device, non_blocking=nb) for k in ("planes", "pi", "z", "legal_mask")}
            targets["n_self"], targets["n_human"] = batch["n_self"], batch["n_human"]
            logged = (step + 1) % p.log_every == 0 or step + 1 in (p.start_step + 1, p.total_steps)
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16, enabled=p.amp):
                logits, value = model(targets["planes"])[:2]
            loss, metrics = mixed_loss(logits, value, targets, p.value_weight, halves=logged)
            if not bool(torch.isfinite(loss)):
                logger.log_status(step, message=f"self-play loss is non-finite at step {step}: stopping",
                                  stage="selfplay", total_steps=p.total_steps, eta_s=None)
                raise RuntimeError(f"self-play loss became non-finite at step {step} (iteration {it}); "
                                   "the model was not updated with it — lower selfplay_lr or resume from the "
                                   "last checkpoint")
            optim.zero_grad(set_to_none=True)
            loss.backward()
            if p.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), p.grad_clip)
            optim.step()
            step += 1
            seen += int(targets["planes"].shape[0])
            if logged:
                last = {k: float(v) for k, v in metrics.items()}
                elapsed = time.time() - t_train
                extra = {k: v for k, v in last.items() if k not in ("loss", "policy_loss", "value_loss", "top1", "top3")}
                logger.log_train(step, loss=last["loss"], policy_loss=last["policy_loss"], value_loss=last["value_loss"],
                                 top1=last["top1"], top3=last["top3"], lr=optim.param_groups[0]["lr"],
                                 pos_per_sec=seen / max(elapsed, 1e-9), gpu_mem_gb=_gpu_mem_gb(p.device),
                                 epoch=float(it), stage="selfplay", buffer=len(buffer), human_mix=p.human_mix,
                                 n_self=batch["n_self"], n_human=batch["n_human"], **extra)
    finally:
        model.eval()
    return step, last


def run_selfplay_stage(
    model: FlyBrain,
    graph: BrainGraph,
    cfg: Any,
    logger: MetricsLogger,
    start_step: int,
    save_checkpoint: Callable[[int, str], Path],
    device: str | torch.device | None = None,
    *,
    optim_state: dict | None = None,
    completed_iters: int | None = None,
) -> int:
    """Alternate self-play generation, mixed training and gating for ``cfg.selfplay_iters`` iterations; returns
    the final step.

    Each iteration (v2, SPEC §6):

    1. the **best** network generates ``cfg.selfplay_games_per_iter`` games (``cfg.mcts_sims`` simulations,
       lockstep batches of ``cfg.selfplay_lockstep_games``; a progress line / status record every 64 finished
       games) → replay buffer;
    2. ``cfg.selfplay_train_steps_per_iter`` AdamW steps (lr ``cfg.selfplay_lr``, batch
       ``cfg.selfplay_batch_size``) on mixed batches: ``cfg.selfplay_human_mix`` of every batch streams from
       the imitation shards (``cfg.shard_name`` series), the rest samples the buffer with the value target
       ``selfplay_value_blend · z + (1 - blend) · q``;
    3. gate (``cfg.selfplay_gate``): the candidate plays the best weights with ``superfly``
       (``cfg.selfplay_gate_games`` games, ``cfg.selfplay_gate_sims`` simulations, paired distinct openings
       from the iteration's games, topped up from :func:`fixed_openings`) and is promoted iff its score
       fraction ≥ ``cfg.selfplay_gate_threshold``; otherwise the weights and the optimizer moments revert to
       their pre-training snapshot (the replay buffer is kept, the iteration counts). An ``elo`` record with
       ``opponent='previous-best'`` (wins/draws/losses, score, threshold, promoted, openings,
       fixed_openings_used, truncated, mean_plies) is logged. A gate that cannot run (the evaluator raises or
       returns nothing) rejects the candidate the same way, logs a ``status`` record with ``gate_error`` and
       raises ``RuntimeError`` — the untested candidate is never promoted;
    4. every ``cfg.selfplay_eval_every_iters`` iterations (and after the last) ``cfg.elo_games`` games as ``fly``
       against a random opponent (``opponent='random'``; without the gate also ``'previous-iteration'``);
    5. ``save_checkpoint(step, 'selfplay')`` (with ``optim=`` when the callback accepts it) → ``ckpt-<step>.pt``
       and ``latest.pt`` hold the best weights, which are also copied to ``best.pt``; a status record with
       ``iteration`` and ``promoted`` marks the iteration as done.

    Resuming: ``completed_iters`` defaults to what the run's metrics say (see :func:`completed_iterations`)
    and ``optim_state`` to the optimizer state of ``<run_dir>/latest.pt`` when that checkpoint was saved by
    this stage at ``start_step``; iterations already done are skipped and ``best.pt`` (when present after at
    least one finished iteration) is loaded as the best network; ``cfg.selfplay_lr`` / the betas / the weight
    decay of the config win over the restored optimizer's. A ``RuntimeError`` (a non-finite loss, a gate that
    could not run) and ``KeyboardInterrupt`` both restore the best weights, save ``latest.pt`` / ``best.pt`` and
    are re-raised.
    """
    device = torch.device(device) if device is not None else next(model.parameters()).device
    iters = int(_get(cfg, "selfplay_iters", 50))
    games_per_iter = int(_get(cfg, "selfplay_games_per_iter", 512))
    sims = int(_get(cfg, "mcts_sims", 100))
    steps_per_iter = int(_get(cfg, "selfplay_train_steps_per_iter", 400))
    batch_size = int(_get(cfg, "selfplay_batch_size", 384))
    human_mix = float(_get(cfg, "selfplay_human_mix", 0.5))
    value_blend = float(_get(cfg, "selfplay_value_blend", 0.5))
    gate = bool(_get(cfg, "selfplay_gate", True))
    gate_games = int(_get(cfg, "selfplay_gate_games", 40))
    gate_sims = int(_get(cfg, "selfplay_gate_sims", 100))
    gate_threshold = float(_get(cfg, "selfplay_gate_threshold", 0.55))
    value_weight = float(_get(cfg, "value_loss_weight", 1.0))
    grad_clip = float(_get(cfg, "grad_clip", 1.0))
    amp = bool(_get(cfg, "amp", True)) and device.type == "cuda"
    log_every = max(1, int(_get(cfg, "log_every", 20)))
    elo_games = int(_get(cfg, "elo_games", 20))
    eval_every_iters = max(1, int(_get(cfg, "selfplay_eval_every_iters", 5) or 5))
    seed = int(_get(cfg, "seed", 0))
    rng = np.random.default_rng(seed + 12345)
    run_dir = Path(getattr(logger, "run_dir", "."))
    if not (0.0 <= human_mix <= 1.0) or not (0.0 <= value_blend <= 1.0):
        raise ValueError("selfplay_human_mix and selfplay_value_blend must lie in [0, 1]")
    gate = gate and gate_games > 0

    if completed_iters is None:
        completed_iters = completed_iterations(run_dir, start_step) if start_step > 0 else 0
    completed_iters = max(0, min(int(completed_iters), iters))
    if optim_state is None and start_step > 0:
        optim_state = _resume_optim_state(run_dir, start_step)

    buffer = ReplayBuffer(int(_get(cfg, "replay_buffer_size", 200_000)), k=max(64, sims), seed=seed + completed_iters)
    weight_decay = float(_get(cfg, "weight_decay", 1e-4))
    groups = param_groups(model, weight_decay)  # same decay rule as imitation: no decay on gains / biases
    lr = float(_get(cfg, "selfplay_lr", 1e-4))
    optim = torch.optim.AdamW(groups, lr=lr, betas=ADAM_BETAS, weight_decay=weight_decay)  # betas as in imitation
    if optim_state is not None:
        try:
            optim.load_state_dict(adapt_optim_state(optim_state, model, weight_decay, groups))
        except (ValueError, KeyError, RuntimeError) as e:
            log.warning("could not restore the self-play optimizer state (%r): starting it fresh", e)
        else:
            for g, fresh in zip(optim.param_groups, groups, strict=True):
                # the checkpoint's hyper-parameters must not win over cfg (the lr is constant here, so unlike
                # imitation nothing re-sets it per step: a changed selfplay_lr on --resume applies from here)
                g["weight_decay"] = fresh["weight_decay"]
                g["lr"] = lr
                g["betas"] = ADAM_BETAS
    step = int(start_step)
    total_steps = start_step + (iters - completed_iters) * steps_per_iter
    t_stage = time.time()
    best_state: dict[str, torch.Tensor] | None = None   # set while the model holds an ungated candidate
    optim_snapshot: dict[str, Any] | None = None         # the optimizer state that goes with best_state
    if completed_iters >= iters:
        logger.log_status(step, message=f"self-play stage already finished ({completed_iters}/{iters} iterations)",
                          stage="selfplay", total_steps=total_steps, eta_s=0.0)
        return step
    resumed_best = _load_best(run_dir, model) if completed_iters > 0 else None
    if resumed_best is not None:
        log.info("resumed the best network from %s (step %d)", run_dir / BEST, resumed_best)
    logger.log_status(step, message=("self-play stage starting" if completed_iters == 0 else
                                     f"self-play stage resuming after iteration {completed_iters}/{iters}"),
                      stage="selfplay", total_steps=total_steps, eta_s=None,
                      **({"best_loaded_step": resumed_best} if resumed_best is not None else {}))

    human: HumanStream | None = None
    n_human = round(batch_size * human_mix)
    if n_human > 0:
        human = HumanStream(cfg, n_human, device, seed=seed + 777 + completed_iters)
        log.info("human mix: %d of every %d training positions stream from %d imitation shard file(s)",
                 n_human, batch_size, len(human.files))
    params = _TrainParams(steps=steps_per_iter, batch_size=batch_size, human_mix=human_mix, value_blend=value_blend,
                          value_weight=value_weight, grad_clip=grad_clip, amp=amp, log_every=log_every, device=device,
                          total_steps=total_steps, start_step=start_step)

    try:
        for it in range(completed_iters, iters):
            # ---- 1. generate games with the best network ------------------------------------------
            t0 = time.time()
            on_game = _Progress(logger, it, iters, games_per_iter, step, total_steps)
            games = generate_games(model, graph, cfg, games_per_iter, device, rng, on_game=on_game, sims=sims)
            gen_s = time.time() - t0
            positions = sum(g.plies for g in games)
            for g in games:
                buffer.add(g)
            lengths = np.array([g.plies for g in games], dtype=np.float64)
            results = {"1-0": 0, "0-1": 0, "1/2-1/2": 0}
            for g in games:
                results[g.result] += 1
            capped = sum(g.capped for g in games)
            log.info("selfplay iter %d: %d games, %d positions in %.1fs (%.1f pos/s), plies mean %.1f, %s, capped %d",
                     it, len(games), positions, gen_s, positions / max(gen_s, 1e-9), lengths.mean() if len(lengths) else 0,
                     results, capped)
            logger.log("selfplay", step, iteration=it, games=len(games), positions=positions, gen_seconds=gen_s,
                       pos_per_sec=positions / max(gen_s, 1e-9), plies_mean=float(lengths.mean()) if len(lengths) else 0.0,
                       plies_min=int(lengths.min()) if len(lengths) else 0, plies_max=int(lengths.max()) if len(lengths) else 0,
                       white_wins=results["1-0"], black_wins=results["0-1"], draws=results["1/2-1/2"], capped=capped,
                       buffer=len(buffer), sims=sims)
            sample = max(games, key=lambda g: (not g.capped, g.plies), default=None)
            if sample is not None:
                logger.log_game(step, pgn=sample.pgn, result=sample.result, moves=(sample.plies + 1) // 2, source="selfplay")
            if games:
                board = chess.Board()
                for uci in sample.moves[: min(len(sample.moves), 20)]:
                    board.push_uci(uci)
                idx, vals = _sample_activity(model, board, device)
                logger.log_activity(step, neuron_idx=idx, values=vals)

            # ---- 2. train the candidate on mixed batches --------------------------------------------
            best_state = {k: v.detach().to("cpu", copy=True) for k, v in model.state_dict().items()}
            optim_snapshot = _copy_optim_state(optim.state_dict())
            t_train = time.time()
            step, last = _train_iteration(model, optim, buffer, human, params, rng, logger, step, it)
            train_s = time.time() - t_train
            done_iters = it + 1

            # ---- 3. gate: candidate vs best with superfly ------------------------------------------
            promoted = True
            gated = False
            if gate:
                openings, n_fixed = _match_openings(games, (gate_games + 1) // 2, rng)
                start_fens = paired_start_fens(openings, gate_games)
                t_gate = time.time()
                gate_error: str | None = None
                try:
                    out = gate_candidate(model, best_state, graph, cfg, device, gate_games, gate_sims, gate_threshold,
                                         start_fens, seed + 1000 + done_iters)
                except Exception as e:  # noqa: BLE001 - whatever broke the evaluator, the candidate is untested
                    out, gate_error = None, repr(e)
                if out is None:
                    # An untested candidate is never promoted: revert to best (weights + optimizer moments), record
                    # why and stop — the operator must fix the gate (SPEC §6); --resume redoes this iteration.
                    gate_error = gate_error or "the gate match could not be played (FlyEngine unavailable or an unexpected match result)"
                    model.load_state_dict(best_state)
                    _restore_optim(optim, optim_snapshot)
                    model.eval()
                    log.error("selfplay iter %d: the gate could not run (%s): candidate rejected, stopping", it, gate_error)
                    logger.log_status(step, message=f"self-play iteration {done_iters}/{iters}: gate could not run "
                                      f"({gate_error}); candidate rejected, weights revert to best, stopping",
                                      stage="selfplay", total_steps=total_steps, eta_s=None, promoted=False, gated=False,
                                      gate_error=gate_error)
                    raise RuntimeError(f"self-play gate could not run in iteration {done_iters} ({gate_error}); the "
                                       "candidate was rejected and the best weights saved — fix the evaluator and "
                                       "resume")
                gated = True
                promoted = bool(out["promoted"])
                logger.log_elo(step, opponent=GATE_OPPONENT, games=int(out["games"]), wins=int(out["wins"]),
                               draws=int(out["draws"]), losses=int(out["losses"]),
                               elo_estimate=float(out["elo_estimate"]), score=float(out["score"]),
                               threshold=gate_threshold, promoted=promoted, openings=int(out.get("openings", 1)),
                               fixed_openings_used=int(n_fixed), truncated=int(out.get("truncated", 0)),
                               mean_plies=float(out.get("mean_plies", 0.0)), sims=gate_sims, iteration=done_iters,
                               seconds=time.time() - t_gate, stage="selfplay")
                verdict = (f"candidate promoted (score {out['score']:.3f} >= {gate_threshold:.2f})" if promoted else
                           f"candidate rejected (score {out['score']:.3f} < {gate_threshold:.2f}), weights revert to best")
                log.info("selfplay iter %d gate vs %s: +%d =%d -%d (%d openings, %d fixed, %d truncated, %d sims, "
                         "Elo %+.0f): %s", it, GATE_OPPONENT, out["wins"], out["draws"], out["losses"],
                         out.get("openings", 1), n_fixed, out.get("truncated", 0), gate_sims, out["elo_estimate"], verdict)
                logger.log_status(step, message=f"self-play iteration {done_iters}/{iters}: {verdict} "
                                  f"(+{out['wins']} ={out['draws']} -{out['losses']} vs {GATE_OPPONENT})",
                                  stage="selfplay", total_steps=total_steps, eta_s=None)
                pgns = out.get("pgns") or ([out["pgn"]] if out.get("pgn") else [])
                if pgns:  # the gate game is the most informative sample: not subject to the per-minute limit
                    logger.log_game(step, pgn=pgns[0], result=_pgn_result(pgns[0]), moves=_pgn_moves(pgns[0]),
                                    source="eval", opponent=GATE_OPPONENT, force=True)
                if not promoted:
                    model.load_state_dict(best_state)
                    _restore_optim(optim, optim_snapshot)   # the moments of a rejected direction go with it
            prev_state = best_state          # the weights the iteration started from (for 'previous-iteration')
            best_state = None                # the model holds the best network again
            optim_snapshot = None
            model.eval()

            # ---- 4. periodic evaluation: vs a random opponent (and vs the previous iteration without a gate) ----
            if elo_games > 0 and (done_iters % eval_every_iters == 0 or done_iters == iters):
                openings = match_openings(games, (elo_games + 1) // 2, rng)
                start_fens = paired_start_fens(openings, elo_games)
                opponents = ["random"] if gated else ["previous-iteration", "random"]
                for opponent in opponents:
                    try:
                        if opponent == "previous-iteration":
                            out = _evaluate_vs_previous(model, prev_state, graph, cfg, device, elo_games,
                                                        start_fens, seed + done_iters)
                        else:
                            out = _evaluate_vs_random(model, graph, cfg, device, elo_games, start_fens,
                                                      seed + done_iters)
                    except Exception as e:  # noqa: BLE001 - evaluation must never kill training
                        warnings.warn(f"evaluation vs {opponent} failed: {e!r}", stacklevel=2)
                        out = None
                    if out is None:
                        continue
                    logger.log_elo(step, opponent=opponent, games=int(out["games"]), wins=int(out["wins"]),
                                   draws=int(out["draws"]), losses=int(out["losses"]),
                                   elo_estimate=float(out["elo_estimate"]), openings=int(out.get("openings", 1)),
                                   iteration=done_iters)
                    log.info("selfplay iter %d vs %s: +%d =%d -%d (%d openings, Elo %+.0f)", it, opponent,
                             out["wins"], out["draws"], out["losses"], out.get("openings", 1), out["elo_estimate"])
                    pgns = out.get("pgns") or ([out["pgn"]] if out.get("pgn") else [])
                    if pgns:  # a sample evaluation game for the dashboard (rate limited by the logger)
                        logger.log_game(step, pgn=pgns[0], result=_pgn_result(pgns[0]), moves=_pgn_moves(pgns[0]),
                                        source="eval", opponent=opponent)

            # ---- 5. checkpoint (= best) + best.pt + status ---------------------------------------------
            ckpt_path = _save(save_checkpoint, step, "selfplay", optim)
            _save_best(run_dir, ckpt_path)
            eta = (time.time() - t_stage) / (done_iters - completed_iters) * (iters - done_iters)
            logger.log_status(step, message=f"self-play iteration {done_iters}/{iters} done "
                              f"({'promoted' if promoted else 'rejected'}; {len(games)} games in {gen_s:.0f}s, "
                              f"{steps_per_iter} steps in {train_s:.0f}s"
                              + (f", loss {last['loss']:.3f}" if last else "") + ")",
                              stage="selfplay", total_steps=total_steps, eta_s=eta, iteration=done_iters,
                              promoted=promoted, gated=gated)

    except KeyboardInterrupt:
        if best_state is not None:  # interrupted while the model held an ungated candidate: latest.pt = best
            model.load_state_dict(best_state)
            model.eval()
        log.warning("interrupted: saving self-play checkpoint (best weights) at step %d", step)
        _save_best(run_dir, _save(save_checkpoint, step, "selfplay", optim))
        logger.log_status(step, message="self-play interrupted (checkpoint saved)", stage="selfplay",
                          total_steps=total_steps, eta_s=None)
        raise
    except RuntimeError:
        if best_state is not None:  # the model held an ungated candidate (non-finite loss, a failed gate): revert
            model.load_state_dict(best_state)
            _restore_optim(optim, optim_snapshot)
            model.eval()
        log.warning("self-play stopped by an error: saving checkpoint (best weights) at step %d", step)
        _save_best(run_dir, _save(save_checkpoint, step, "selfplay", optim))
        raise
    logger.log_status(step, message="self-play stage finished", stage="selfplay", total_steps=total_steps, eta_s=0.0)
    return step


def _pgn_result(pgn: str) -> str:
    for token in ("1-0", "0-1", "1/2-1/2"):
        if f'[Result "{token}"]' in pgn:
            return token
    return "*"


def _pgn_moves(pgn: str) -> int:
    """Full moves in a PGN string (0 if it does not parse)."""
    game = chess.pgn.read_game(io.StringIO(pgn))
    if game is None:
        return 0
    plies = sum(1 for _ in game.mainline_moves())
    return (plies + 1) // 2


__all__ = [
    "BEST",
    "GATE_OPPONENT",
    "Game",
    "HumanStream",
    "ReplayBuffer",
    "completed_iterations",
    "elo_from_score",
    "fixed_openings",
    "gate_candidate",
    "generate_games",
    "human_targets",
    "make_mixed_batch",
    "match_openings",
    "mixed_loss",
    "opening_fens",
    "paired_start_fens",
    "play_match",
    "run_selfplay_stage",
    "selfplay_loss",
]
